<?php

namespace Kiwilan\Typescriptable;

use Kiwilan\Typescriptable\Typed\Eloquent\EloquentConfig;
use Kiwilan\Typescriptable\Typed\EloquentType;
use Kiwilan\Typescriptable\Typed\RouteType;
use Kiwilan\Typescriptable\Typed\SettingType;

class Typescriptable
{
    /**
     * @var string[]
     */
    const TS_HEAD = [
        '/* eslint-disable eslint-comments/no-unlimited-disable */',
        '/* eslint-disable */',
        '/* prettier-ignore */',
        '// @ts-nocheck',
        '// Generated by laravel-typescriptable',
    ];

    public static function head(): string
    {
        return implode(PHP_EOL, self::TS_HEAD);
    }

    public static function models(EloquentConfig $config): EloquentType
    {
        return EloquentType::make($config)->execute();
    }

    public static function routes(string $json_output, bool $with_list, string $output_path): RouteType
    {
        return RouteType::make($json_output, $with_list, $output_path);
    }

    public static function settings(string $settings_path, string $output_path, string $extends): ?SettingType
    {
        return SettingType::make($settings_path, $output_path, $extends);
    }
}
